models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    class_weight: "balanced"
    random_state: 42

  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    random_state: 42 